### ISSUE TITLE
SPO2 Index-out-of-range error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hamalawy/telehealth#17]
```
Traceback (most recent call last):
  File "spo2_demo.py", line 137, in spo2_timer1
    self.spo2.get()
  File "/home/rxbox/Desktop/New Folder/SPO2.py", line 87, in get
    self.parse_packet(data_packet)
  File "/home/rxbox/Desktop/New Folder/SPO2.py", line 95, in parse_packet
    sig_quality = packet[5]
IndexError: list index out of range

```

Original issue reported on code.google.com by `markjanb...@gmail.com` on 19 Jan 2010 at 6:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `luis.si...@gmail.com` on 17 Aug 2010 at 8:52
- Changed state: **Done**
